apiVersion: v1
kind: ConfigMap
metadata:
  name: twem-config
  namespace: memcache
data:
  nutcraker.yaml: |
    memcache:
      listen: 0.0.0.0:11211
      hash: fnv1a_64
      distribution: ketama
      redis: false
      preconnect: true
      auto_eject_hosts: true
      timeout: 10000
      server_retry_timeout: 2000
      server_failure_limit: 1
      server_connections: 200
      servers:
        - memcache-0.memcache.memcache.svc.cluster.local:11211:1 memcache00
        - memcache-1.memcache.memcache.svc.cluster.local:11211:1 memcache01
        - memcache-2.memcache.memcache.svc.cluster.local:11211:1 memcache02
        - memcache-3.memcache.memcache.svc.cluster.local:11211:1 memcache03

