---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: memcache
  namespace: memcache

spec:
  serviceName: "memcache"
  replicas: 4
  template:
    metadata:
      labels:
        app: "memcache"
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: memcache
        image: memcached
        ports:
        - containerPort: 11211
          name: memcache
        resources:
          limits:
            memory: 3500Mi
          requests:
            memory: 3000Mi
      - name: memcached-exporter
        image: prom/memcached-exporter
        imagePullPolicy: Always
        name: memcached-exporter
        ports:
        - containerPort: 9150
          protocol: TCP

