apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testrolebinding
  namespace: perms
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: test_role
subjects:
- kind: ServiceAccount
  name: testuser
  namespace: perms
